name: Book Tennis Court

on:
  schedule:
    - cron: '45 22 * * *'  # runs at 5:45 AM Jakarta (UTC+7 = 22:45 UTC)
  workflow_dispatch:

jobs:
  book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run booking script
        run: node booking.js
