name: Tennis Booking

on:
  workflow_dispatch:   # Manual trigger for testing
  schedule:
    - cron: '50 22 * * *'  # Runs at 22:50 UTC (convert to your timezone)

jobs:
  book-tennis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run booking script
        run: npm start
