name: Booking Tennis Court
- name: Clean cache (optional)
  run: rm -rf node_modules package-lock.json

on:
  workflow_dispatch:
  schedule:
    - cron: "45 10 * * *" # 10:45 UTC ~ 17:45 Jakarta time, adjust as needed

jobs:
  booking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run booking script
        run: npm start
